version: '2'
services:
  mongo-container:
    image: "mongo:6"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root-test-password
    ports:
      - "27017:27017"